import React, { useEffect, useState } from 'react';
import { getHistory } from '../services/api';
import { Link } from 'react-router-dom';

function Dashboard() {
  const [history, setHistory] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {
      const data = await getHistory();
      setHistory(data);
    } catch (error) {
      console.error("Failed to fetch history:", error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-gray-800">My Dashboard</h1>
        <Link to="/builder" className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">
          Create New Resume
        </Link>
      </div>

      {isLoading ? (
        <div className="text-center py-10">Loading history...</div>
      ) : history.length === 0 ? (
        <div className="bg-white p-10 rounded-lg shadow text-center">
          <p className="text-gray-500 mb-4">No resumes generated yet.</p>
          <Link to="/builder" className="text-blue-600 hover:underline">Start building your first resume</Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {history.map((item) => (
            <div key={item.id} className="bg-white p-6 rounded-lg shadow hover:shadow-lg transition">
              <h3 className="text-xl font-semibold mb-2">{item.name || 'Untitled Resume'}</h3>
              <p className="text-gray-600 text-sm mb-4">Created: {new Date(item.created_at).toLocaleDateString()}</p>
              <div className="flex space-x-2">
                {/* We don't have a way to re-download the exact file yet without regenerating or storing the file. 
                    For now, let's just show the metadata. 
                    Ideally, we should store the 'resume_text' in DB and allow re-download. 
                    I'll add a simple 'View' button if we had a detail page, but for now just a list is good. 
                */}
                <span className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded">Generated by AI</span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default Dashboard;
